### ISSUE TITLE
AtomicOption tag could be simpler

### ISSUE THREAD

**Issue by KillingSpark** [Alonely0/Lariv#1]
As far as I can see, the AtomicOption::tag can just be inside the RwLock. It is only used when the lock is taken and only written if the RwLock is locked via RwLock::write.

So It could be inlined into the value of the RwLock 

```rust
pub struct AtomicOption<T> {
    value: RwLock<(bool, MaybeUninit<T>)>,
}
```

Which should be equivalent to just wrapping an `RwLock<Option<T>>` in a new type?

**Comment by Alonely0** [comment]
It used to be separated for some aggressive optimizations that the lack of features during the early stages of the project used to enable. Now it's true it could be reduced to a simple `RwLock<Option<T>>`, so I will look into it. Either way, this implementation allows more control over its overall behavior, which could be useful down the line (reordering certain operations, for example).

I am pretty sure that being able to read the discriminant without interacting with the `RwLock` is something that both the optimizer and the CPU's speculation heuristics probably like. Moreover, an `Option`'s discriminant is AFAIK an `isize`, while an `AtomicBool` is just an `u8`. This probably comes in handy for cutting down memory usage and increasing cache locality, and probably is the main reason I'll continue using this implementation (unless there are big performance gains to be had with a regular `Option`).

Nevertheless, thanks for the insight!

**Comment by KillingSpark** [comment]
`Option<T>` would have the advantage of the compiler inlining the discriminant into the value if possible (i.e. `NonNull<>` or references) but it's true, adding the explicit AtomicBool might open up optimizations. I just noticed that that is currently not used anywhere.

**Comment by Alonely0** [comment]
Closing as per #5.
