### ISSUE TITLE
Indeces can get reused without a way of the holder of an index being able to check that

### ISSUE THREAD

**Issue by KillingSpark** [Alonely0/Lariv#3]
Lariv tries to fill empty spaces before allocating a new node which results in indeces being reused. But there is no way to check if the value is still the "same". 

This is motivated by usecases like connections being stored in this where one thread manages the insertion/removal of the connections and other threads are responsible for using them, only identified by the LarivIndex. A thread using an old index should always see that the index it is holding is no longer valid even if the slot in the Lariv got reused.

Maybe the slots could have an epoch counter, which gets included into the lariv index. If an element is put into a slot the respective counter is incremented. And the various operations like get/take/... only work if the counter in the index still matches the current counter of the slot.

This could be implemented with a counter in the `AtomicOption` and changing the signature of `AtomicOption::get` `AtomicOption::get_mut` to take an additional parameter that indicates the expected counter value.

Example of current behaviour:

```rust
#[test]
pub fn index_reuse() {
    let lariv = Lariv::<u32>::new(10);

    let original_idx = lariv.push(1);

    // Fill all other slots
    for _ in 0..9 {
        lariv.push(0);
    }

    // remove the original element
    lariv.remove(original_idx);
    assert!(lariv.get(original_idx).is_none()); // I'd expect this to always return None in the future

    // push new element, this will reuse the original index
    let new_idx = lariv.push(2);
    
    assert!(lariv.get(original_idx).is_none()); // <-- this fails because the index got silently reused
}
```

**Comment by Alonely0** [comment]
That went completely under my radar. I'll fix it, thanks!
